eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka/

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/erepo_accounts?currentSchema=erepo_default
    username: postgres
    password: {cipher}ab6f8514bcde51cd27c20f91c14af26781a6d4753441508606e93a842becb8d3
   # password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.xml